python main_test.py \
--image_dir /project/wli5/JIMA/data/iu_xray/images/ \
--ann_path /project/wli5/JIMA/data/iu_xray/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 16 \
--epochs 100 \
--save_dir results/iu_xray \
--step_size 50 \
--gamma 0.1 \
--seed 9223 \
--load /project/wli5/JIMA/data/model_iu_xray.pth
